add express
missionctrlbiz/Conquistadors-Group-1 pull request #2
Opened 2024-06-05 17:33 UTC by itumo147

I setup express backend for devs

2024-06-05 17:40 UTC, Profsain commented on backend/.gitignore
> +node_modules
check this.
node_modules folder not ignored

2024-06-05 17:41 UTC, Profsain requested changes
Remove node_modules folder.

2024-06-05 20:35 UTC, missionctrlbiz approved these changes

2024-06-05 20:36 UTC, missionctrlbiz commented
I asked to request the review by updating the status although I have approved it

2024-06-05 20:40 UTC, missionctrlbiz approved these changes

2024-06-05 20:41 UTC, missionctrlbiz approved these changes

2024-06-05 20:48 UTC, merged

2024-06-07 14:14 UTC, missionctrlbiz reviewed
Added Express and cors